### ISSUE TITLE
Update event handling for oF 0.9

### ISSUE THREAD

**Issue by mruegenberg** [paulobarcelos/ofxWarpBlendTool#2]
When trying to build with oF 0.9.2, I get multiple errors like `error: ‘mouseScrolled’ is not a member of ‘ofxWarpBlendTool::Controller’`. This is probably because oF 0.9 handles some new events.

Adding an empty implementation for the problematic methods to `ofxWarpBlendTool.h` seems to solve the problem:

```
// ...
void mouseReleased(ofMouseEventArgs & args);

void mouseScrolled(ofMouseEventArgs &mouse) { ; }
void mouseEntered(ofMouseEventArgs &mouse) { ; }
void mouseExited(ofMouseEventArgs &mouse) { ; }
```

**Comment by paulobarcelos** [comment]
Same here, could you do a pull request?

On Tuesday, 3 May 2016, Marcel Ruegenberg notifications@github.com wrote:

> When trying to build with oF 0.9.2, I get multiple errors like error:
> ‘mouseScrolled’ is not a member of ‘ofxWarpBlendTool::Controller’. This
> is probably because oF 0.9 handles some new events.
> 
> Adding an empty implementation for the problematic methods to
> ofxWarpBlendTool.h seems to solve the problem:
> 
> // ...
> void mouseReleased(ofMouseEventArgs & args);
> 
> void mouseScrolled(ofMouseEventArgs &mouse) { ; }
> void mouseEntered(ofMouseEventArgs &mouse) { ; }
> void mouseExited(ofMouseEventArgs &mouse) { ; }
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/paulobarcelos/ofxWarpBlendTool/issues/2

## 

Sent from my iPhone
